[package]
name = "spring-web"
description = "Integration of rust application framework spring-rs and Axum web framework"
version = "0.4.6"
categories = ["web-programming::http-server"]
keywords = ["web-programming", "web-server", "spring"]
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = ["http2"]
http2 = ["axum/http2"]
multipart = ["axum/multipart"]
ws = ["axum/ws"]

[dependencies]
spring = { path = "../spring", version = "0.4" }
spring-macros = { path = "../spring-macros", version = "0.4" }
axum = { workspace = true, features = ["macros"] }
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tokio = { workspace = true, features = ["full"] }
tower = { workspace = true, features = ["full"] }
tower-http = { workspace = true, features = ["full"] }
byte-unit = { workspace = true, features = ["serde"] }
schemars = { workspace = true }
inventory = { workspace = true }

[dev-dependencies]
spring-sqlx = { path = "../spring-sqlx" }
